### ISSUE TITLE
Dear researcher, I found that there is no json file.

### ISSUE THREAD

**Issue by fly2tortoise** [TT2408/nasrobbench201#1]
FileNotFoundError: [Errno 2] No such file or directory: 'meta.json'

![image](https://github.com/TT2408/nasrobbench201/assets/85298331/d5494402-d0d0-4708-a5ed-ed8b550ce7de)

**Comment by TT2408** [comment]
Hey, you can download at https://drive.google.com/drive/folders/1Hhv2R1EfpnQOAyClX09mj7rj1Zbbbj0G
