### ISSUE TITLE
Dear researcher, I have a little confuse. 

### ISSUE THREAD

**Issue by fly2tortoise** [TT2408/nasrobbench201#2]
Dear researchers, I have some doubts about the variation of isomorphic performance. I found that individuals #19 and #29 within B201 of ICLR23 are isomorphic and identical in performance.
![image](https://github.com/TT2408/nasrobbench201/assets/85298331/4fa2619d-170c-4843-a380-ae77fc82baea)

However, I have found that the performance of two differently constructed architectures in NAS-RB-201 is consistent.
![image](https://github.com/TT2408/nasrobbench201/assets/85298331/e2904980-1d5f-4bca-9c8e-12d010eca2b0)

Two isomorphic architectures perform differently. 
![image](https://github.com/TT2408/nasrobbench201/assets/85298331/1a1950f3-79eb-4901-8fd4-70bd88abf600)

Very thankful！

**Comment by TT2408** [comment]
Hi,

Thanks for pointing out this issue. This is due to the visualization where # 1 and # 2 should be inversed, #5 and #6 should be inversed. It is fixed now.

Best regards
