### ISSUE TITLE
Two small questions. Thank you.

### ISSUE THREAD

**Issue by fly2tortoise** [TT2408/nasrobbench201#4]
Respected researchers：

The optimal precision in the clean part of Table 2 is 0.794, but the effect of local Search is 0.796.Is it written wrong? 
![image](https://github.com/TT2408/nasrobbench201/assets/85298331/53a1866f-8d66-4c9f-b7bc-a0bed18f8d77)

The open source code doesn't seem to have the algorithm described in table7, can the author share it? Especially DARTS and AdvRush in Rob-NAS-201. 
This is very helpful, thanks!
![image](https://github.com/TT2408/nasrobbench201/assets/85298331/b26fc762-a8b1-43be-8dec-e8fee815c3c2)

Thank you.

**Comment by TT2408** [comment]
Hi, we select the architecture with the highest robust accuracy. Therefore, its clean accuracy might not be the highest. We use the official code of darts and advrush.
